import { EditorState } from "./types";

// Initial editor state
export const createInitialState = (): EditorState => ({
  lines: [
    "Welcome to the Vim Simulator!",
    "This is a functional Vim editor built in React + TypeScript.",
    "",
    "Try these commands:",
    "- Press 'i' to enter Insert mode",
    "- Press 'v' to enter Visual mode",
    "- Press 'h/j/k/l' to move cursor",
    "- Press ':' to enter Command mode",
    "- Press 'x' to delete character",
    "- Press 'dd' to delete line",
    "- Press 'yy' to yank (copy) line",
    "- Press 'p' to put (paste)",
    "- Press 'u' to undo",
    "- Press 'Ctrl+r' to redo",
    "- Try 'diw' to delete inner word",
    "- Try 'ci\"' to change text inside quotes",
    "",
    "Start editing and experience Vim's modal power!",
    "",
    "-- Happy Vimming! --",
  ],
  cursor: { line: 0, column: 0 },
  mode: "NORMAL",
  registers: {},
  undoStack: [],
  redoStack: [],
  commandBuffer: "",
  statusMessage: "-- NORMAL --",
  lastCommand: "",
  countPrefix: "",
  operatorPending: undefined,
  lastMotion: undefined,
  lastOperator: undefined,
  lastTextObject: undefined,
});
